### ISSUE TITLE
Bug in example 1, hello world regex has \\s instead of \s

### ISSUE THREAD

**Issue by chrisdolan** [C2FO/nools#123]
Code is:

    m : Message m.text =~ /^hello(\\s*world)?$/

Code should be:

    m : Message m.text =~ /^hello(\s*world)?$/

**Comment by doug-martin** [comment]
If you are using the DSL you now dont have to escape `\` characters inside of a regex, if you are creating the rules programatically you still will have to escape since its a string. Let me know if you have any issues.

-Doug
