### ISSUE TITLE
compile callback

### ISSUE THREAD

**Issue by shacal** [C2FO/nools#127]
Compile function does work when using callback,

Dont null cb, use it if it exists... Need to change lib/index.js and compile/index.js

exports.compile = function (file, options, cb) {
    if (extd.isFunction(options)) {
        cb = options;
        options = {};
    } else {
        options = options || {};
        // TO FIX
        // cb = null;
    }

**Comment by DevSide** [comment]
you're right, https://github.com/C2FO/nools/blob/master/lib/compile/index.js#L153

**Comment by DevSide** [comment]
Thanks !
