### ISSUE TITLE
HOWTO: Storing and reading rules from MongoDB

### ISSUE THREAD

**Issue by assimoes** [C2FO/nools#128]
Is it possible to store nools rules in a MongoDb (or any other document store for that matter) database? How would one inject them into a session?

**Comment by bthibault** [comment]
Yes I have my own DSL that I use to store a rule in Mongo... then I pull it out the rules and build up the programmatic expression:

ex. :  {  rule_id: 01234, 
            action: 'adjust', 
            comparator: '>', 
            param: 'price' ,
    ....

**Comment by assimoes** [comment]
Thank you to both, this was helpful

**Comment by harshad-mohape** [comment]
> Yes I have my own DSL that I use to store a rule in Mongo... then I pull it out the rules and build up the programmatic expression:
> 
> ex. : { rule_id: 01234,
> action: 'adjust',
> comparator: '>',
> param: 'price' ,
> ....
> 
> then in the code :
> 
> var expression = buildExpression(action, condition, param);

Can you provide a detailed example of it?
