### ISSUE TITLE
Rule Pattern Sequence Changes Outcome

### ISSUE THREAD

**Issue by cbrady321** [C2FO/nools#129]
I have been trying out rules and building a few support functions to emulate the Drools features such as lock-on-active and no-loop.  I found a situation where the order of patterns in a rule changes whether the rule fires.

The following loops forver:
rule Hello {
    when {
        m : Generic isLockOpen(m, "Hello");
        m : Generic m.text =~ /hello (world)?/;
    }
    then {
        setLock(m, "Hello");
        modify(m, function(){ this.text += "goodbye"; });
    }
}

However, reordering the patterns leads to a working rule.
    when {
        m : Generic m.text =~ /hello (world)?/;
        m : Generic isLockOpen(m, "Hello");
    }

Is the problem on my end? I assumed that the multiline constraints such as OR implied that the top-level rules work the same way. (https://github.com/C2FO/nools#or-constraint)

**Comment by DevSide** [comment]
Probably linked to #154

**Comment by DevSide** [comment]
You have two variables called `m`  ?
