### ISSUE TITLE
how can I reuse a session between flows?

### ISSUE THREAD

**Issue by rahpuser** [C2FO/nools#139]
I have a fallback requirement. I have to evaluate two set of rules, one is specific by user and the other one is general in the system, if no rule is fired in the more specific context I have to do a fallback to the more general rules which are the default set of rules for the system.

So far I'm storing the set of rules in flows. So I execute the match function on a session of the specific flow, and if no rule is fired, I ask for a new session for the default/general flow that contain the default/general rules.

So I have the following questions:
1. Is possible to share a session between flows?
   1.1  Does opening two session for the same purpose affect performance?
2. Is this the right path to follow?
3. Can I create a single flow for the two scenarios?
    Taking a consideration that rules are modified, deleted or added on the fly.

Thanks.

**Comment by bthibault** [comment]
@rahpuser can you provide a little more detail around the needed execution logic?

**Comment by doug-martin** [comment]
@rahpuser it sounds like this would be a situation where you could use [agenda groups](https://github.com/C2FO/nools#agenda-groups). 

For example you could set up two agenda groups `user-specific` and the default one set the `focus` to `user-specific` this would ensure that any user specific rule would fire first then after there are no more rules to fire in that group it would fall back to the default one. If you always wanted to fire user events first you could just set those rules to auto focus.

Let me know if this helps.

-Doug

**Comment by rahpuser** [comment]
@doug-martin that work for me. Thanks
