### ISSUE TITLE
test the browser examples locally

### ISSUE THREAD

**Issue by abderrahmengharsallah** [C2FO/nools#148]
i know that my question might be stupid but i'am new in the programming field specially node.js ; 
when I've tried to execute the diagnosis.html i didn't get any result so how do i proceed to try the examples locally

**Comment by doug-martin** [comment]
To run the examples I do the following.

1. `npm install -g node-static`, you can use any server but [node-static](https://www.npmjs.com/package/node-static) is pretty easy to use 
2. cd to the nools source directory
3. Type `static` at the command prompt
4. Visit <http://localhost:8080/examples/browser/diagnose.html>

Let me know if you have any issues

**Comment by abderrahmengharsallah** [comment]
it worked, thank you very much.
but why when i just run the browser it didn't work 
![image](https://cloud.githubusercontent.com/assets/6849495/6445014/b40c3002-c101-11e4-9e7b-f0fc04d6f8a0.png)
even when i've loaded those files manually i didn't get anything
