### ISSUE TITLE
Stop matching

### ISSUE THREAD

**Issue by fabrigm** [C2FO/nools#149]
I'm working in a web app that calls match when the mouse moves inside a div, my question is:

How can I stop matching before I call match again?

Thanks

**Comment by doug-martin** [comment]
Thanks to PR #143 you can now call halt even when using .match....so you should be able to call `session.halt()` to stop execution, however you should still wait until the `.match` promise resolves to be sure that the execution is done.

Please reopen if you still have issues

-Doug

**Comment by fabrigm** [comment]
I hadn't seen session.halt(). Thanks for all your work!!
