### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by vjaitly** [C2FO/nools#155]
I am trying to use nools as a service. However i am getting inconsistent values for same facts in each run. This is what I have done -
Used restify to expose a REST API for clients to call the nools engine.
On the handler I compile the flow which is dynamically generated from the rules definition stored in MongoDB. Also based on the parameters passed to the API a set of facts get asserted for that particular session.( each request will load a different flow).
When I make the calls to the API one at a time the results are as expected. However, when I concurrently fire ( I am testing currently with 4 requests) , randomly one of the requests are not returning the expected results. The same request called separately works fine.
Any pointer on where to look for the issue?
I am calling the session.dispose() after match and also deleteFlow() for a request once the engine returns the data.
I am using DSL rather than programmatic way, and these DSLs are generated on runtime using handlebars templates.
I have checked for the facts before the session.match() call and all the facts seem to be correct. Are there any known issues in case of concurrent calls or multiple flows in parallel ?

**Comment by DevSide** [comment]
Each request should have its own Nools' scope. If you get concurrency issues, it's probably with your database transactions/ORM.
