### ISSUE TITLE
white space significant in nools rule constraints, when it shouldn't be.  source of easy errors.

### ISSUE THREAD

**Issue by williamwsmith** [C2FO/nools#157]
This constraint compiles/executes:

  dw : DimensionalWeight dw.value != null  && (dw.valid == null || dw.valid == false);

While this one does not:

dw : DimensionalWeight dw.value !=null  && (dw.valid == null || dw.valid == false);

The white space between the "!=" and the "null" has been removed.

**Comment by DevSide** [comment]
I looks like this is a specific bug with `null` and the whitespace.

```
var indexOf = definedFuncs.indexOf; var hasOwnProperty = Object.prototype.hasOwnProperty;return function matcher0(fact, hash){var dw = hash.dw;var null = fact.null; return !!(dw['value'] == null);}

SyntaxError: Unexpected token null
    at exports.toJs (nools/lib/constraintMatcher.js:441:13)
    at Object.exports.getMatcher (nools/lib/constraintMatcher.js:448:12)
```

**Comment by DevSide** [comment]
#204
