### ISSUE TITLE
is this a bug

### ISSUE THREAD

**Issue by taoqf** [C2FO/nools#169]
i can use
when
then
in drools
but i cannot use it in nools, there must be a Constraints at least.
is this a bug in nools?

**Comment by markbjerke** [comment]
I"m not sure , you are asking for an empty rule correct ? Cant you just place a constraint that matches on Object  and make the problem go away ?

**Comment by taoqf** [comment]
yes, i do this in this way for now.
but i wish, it could be fixed someday.
