### ISSUE TITLE
Or together with when

### ISSUE THREAD

**Issue by bwired-nl** [C2FO/nools#186]
Hi 
Im trying to do this
The When M1 True and if 1 of the OR is true it should be triggered

example: if M1 and only M5 is true i should be able to catch this with
if (m5.changed) {
  do something
}

This seems to only trigger the first one the  OR?

``
rule alarmtriggerd {
    when {
		m1: Message m1.t == 'visonic/alarm' && m1.p != 'armedaway';
		or (m2: Message m2.t == 'sonic/zone2' && m2.changed,
		     m3: Message m3.t == 'sonic/zone4' && m3.changed,
		     m4: Message m4.t == 'sonic/zone6' && m4.changed,
		     m5: Message m5.t == 'sonic/zone10' && m5.changed,
		     m6: Message m6.t == 'sonic/zone11' && m6.changed,
		     m7: Message m7.t == 'sonic/zone13' && m7.changed,
	             m8: Message m8.t == 'sonic/zone16' && m8.changed
		);
		}
    then {
if (m5.changed) {
  do something
}
if (m6.changed) {
  do something
}

etc.
}

**Comment by DevSide** [comment]
You should split your rule and really avoid `if` condition in the Right hand side (Then).

```
when {
  m1: Message m1.t == 'visonic/alarm' && m1.p != 'armedaway';
  m2: Message m2.t == 'sonic/zone2' && m2.changed
}
then {
  ... do something with m2
}
```
