### ISSUE TITLE
Security Issues with uglify

### ISSUE THREAD

**Issue by vikeen** [C2FO/nools#196]
@dustinsmith1024 and @doug-martin, I got the following email this morning.

> Hi, I’m using the node js Nools and I noticed that there are some issues with uglify-js:
> 
> https://nodesecurity.io/advisories/39
> https://nodesecurity.io/advisories/48
> 
> I would like to ask if you plan to release new version of Nools with newer version of uglify-js?

A quick looked like this were both worthy issues to address. It looks like we can just update uglify-js, run the build and test suite, and push up a patch fix.

**Comment by DevSide** [comment]
Could you make a PR to upgrade uglify ?
