### ISSUE TITLE
Defined helper function Date is rather confusing.

### ISSUE THREAD

**Issue by kidrane** [C2FO/nools#96]
This Date is quite different from the built-in function Date.
I have define rules as following:
```` javascript
	flow.rule("coupons expire",
		[[Coupon, "coupon", "coupon.valid && coupon.duedate < Date.now()"]],
		function(facts){
			facts.coupon.valid = false;
			this.modify(facts.coupon);
		});
````

I know I can use now() instead, but I expect Date.now() should work as it works all around the javascript world.

**Comment by DevSide** [comment]
If you need the timestamp, you can use this trick `coupon.duedate < now().valueOf()`
